Feat. 원샷 프레임 분류 및 일치율 분석
KrossCutting/KrossCutting-server pull request #10
Opened 2024-02-08 16:56 UTC by sht02048

# KanBan Title
- [원샷 프레임 분류 및 일치율 분석](https://minsug.notion.site/Server-compliations-POST-9792742043cd452da63beabb96c28746?pvs=4)

# Tasks in detail - checkList
- [x]  메인 - 서브1 일치율 비교
- [x]  메인 - 서브2 일치율 비교
- [x]  두 일치율을 비교하여 더 일치율이 높은 영상을 선택

# Description
- 원샷 알고리즘을 각 영상마다 진행한 후에 반환되는 배열을 받아 메인 프레임을 기준으로 서브 1과 2 프레임을 분류합니다. 만약 같은 시간대에 서브 1과 2 모두 원샷으로 판별된다면 일치율 비교를 통해 더 높은 일치율을 가진 프레임을 반환합니다. 일치율 분석은 움직임 분석을 기반으로 했으며 움직임이 없는 부분은 검은색으로 표현되는데 원샷 프레임의 모든 검은색을 확인하여 서브 프레임의 같은 index 픽셀에도 검은색인지 체크합니다. 

# Concern
- frame을 직접적으로 사용하는 `convertFrameToBinaryArray`만 `services`에 넣고 나머지는 `uti`에 넣었는데 이게 과연 합리적인지 판단부탁드립니다. 제 근거는 `frame`을 다루는 로직은 `services`에 `Index`와 숫자를 다루는 로직은 `util`애 넣는 것이 적합하다고 생각했습니다.

# Remarks
- 아직 컨트롤러가 구체적으로 어떤 매개변수를 받는지 몰라 임의로 설정했으며 추후 변경이 필요합니다. 
- `convertFrameToBinaryArray`애 path를 다루는 부분이 많은데 추후 수진님이 생성한 constants가 main으로 머지되면 업데이트가 필요합니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-09 03:57 UTC, alswla requested changes
민석님! 모든 엣지 케이스에 대해 고민해보신 것 같습니다! 추후 에러핸들링 과정시 도움이 될 것 같습니다! 리뷰 확인 부탁드리겠습니다 🙇‍♀️

2024-02-09 03:57 UTC, alswla commented on routes/controllers/chooseFrame.controller.js
> +  validateArrays(mainFrames, subOneFrames, subTwoFrames);
해당 함수 확인하니 타입안정성을 위한 로직을 별도 유틸로 분리해주신걸로 확인했습니다! 👍

다만 해당 함수에 대한 적절한 에러 핸들링을 현재 코드에서는 해주지 못하고 있는 것 같습니다.
하나의 인자라도 배열이 아닐 경우 에러를 발생시키는데 이 부분에 대해서 에러 핸들링 처리가 필요해 보입니다.

오늘 스크럼때 에러핸들링 칸반 추가되었으니 안정화 작업때 같이 처리할 수 있도록 TODO로 남겨주시면 좋을 것 같습니다 ✨

2024-02-09 03:57 UTC, alswla commented on routes/controllers/chooseFrame.controller.js
> +    sortCommonFrames(mainFrames, subOneFrames, subTwoFrames);
민석님! 현재 최대값인 3개의 동영상을 가정하고 로직을 구현하고 있지만 서비스 함수에 3개의 파일이 모두 있다고 가정하고 작업하는 것은 이후 리팩토링시 어려움이 있을 것 같아 서비스 함수는 모든 경우에 사용할 수 있도록 하고 컨트롤러에서 3개의 영상을 가정하고 작업해주신다면 좋을 것 같습니다! (혹은 if문 분기처리) 👍 

(이 경우에는 하나라도 정의되지 않으면 레퍼런스 에러가 발생될 것 같습니다!)

2024-02-09 03:57 UTC, alswla commented on routes/controllers/chooseFrame.controller.js
> +      const [mainBinary, subOneBinary, subTwoBinary] =
해당 부분도 위에서 남긴 코멘트와 동일합니다! (분기처리)
추가로 `mainBinary`에서 좀 더 자세한 `mainPixelBinary`라는 변수명도 좋을 것 같다는 의견입니다!👍

2024-02-09 03:57 UTC, alswla commented on routes/controllers/chooseFrame.controller.js
> +      const subTwoPercent = getMatchedPercent(mainBinary, subTwoBinary);
일치율을 계산하고 해당 일치율의 값을 담고 있는 변수이기 때문에 `subOneMatchRate`도 좋을 것 같다는 의견입니다! :)

2024-02-09 03:57 UTC, alswla commented on services/convertFrameToBinaryArray.js
> +      }
프레임의 픽셀 위치에 대해서 색상(검정/흰색)을 비교해서 일치율을 구해주시는군요!👍

다만 한가지 굼금한점은, 해당 부분에서 중첩배열을 써주시는 이유가 있을까요?🤔 
모든 전처리된 프레임 이미지의 경우 200 * 200 처리된 픽셀이고, 
일치율을 비교하기 위해서라면 1차원 배열과 중첩배열의 픽셀 순서는 동일할 것 같다는 의견입니다! 

만약 1차원 배열만으로 비교에 문제가 없다면 for문 하나로도 일치율을 구할 수 있을 것 같다는 생각입니다 😉

2024-02-09 03:57 UTC, alswla commented on util/getMatchedPercent.js
> +  }
앞선 코드부터 느꼈지만 모든 예외상횡의 경우에 대해 고려해보신 것 같습니다!👍 민석님 덕분에 이후 에러 핸들링 작업시에도 도움이 될 것 같습니다

2024-02-09 03:57 UTC, alswla commented on util/getMatchedPercent.js
> +const BLACK = 0;
별도로 상수처리를 통해 명시적으로 나타내주셨군요 👍

2024-02-09 03:57 UTC, alswla commented on util/sortCommonFrames.js
> +function sortCommonFrames(mainFrames, subOneFrames, subTwoFrames) {
추가로 해당 함수도 이후 분기처리 진행되면 좋을 것 같습니다! 👍

2024-02-09 05:02 UTC, sht02048 commented on routes/controllers/chooseFrame.controller.js
> +    sortCommonFrames(mainFrames, subOneFrames, subTwoFrames);
해당 컨트롤러는 서브 1과 서브 2 프레임 중 메인 프레임과 일치율이 더 높은 프레임을 분류하는 목적을 가지고 있는데 만약 클라이언트에서 메인과 서브 영상 하나만을 전달하면 해당 컨트롤러의 목적을 잃어버리기에 실행시켜도 되지 않을 것 같습니다! 

정리드리자면 메인과 서브 영상 하나만 서버로 전달된다면 일치율이 더 높은 프레임을 찾을 필요가 없어 `chooseFrame`의 매개변수를 수정하지않아도 될 것 같습니다!

2024-02-09 05:02 UTC, sht02048 commented on routes/controllers/chooseFrame.controller.js
> +      const [mainBinary, subOneBinary, subTwoBinary] =
의견 감사합니다!

2024-02-09 05:04 UTC, sht02048 commented on routes/controllers/chooseFrame.controller.js
> +      const subTwoPercent = getMatchedPercent(mainBinary, subTwoBinary);
저도 `percent`가 조금 이상했는데 ㅎㅎㅎ 감사합니다

2024-02-09 05:06 UTC, sht02048 commented on services/convertFrameToBinaryArray.js
> +      }
맞네요 민지님! 이미 흑백으로 전처리된 이미지로 1차원 배열로 해결할 수 있네요! 프로세스 시간이 단축이 되겠네요. 꼼꼼하게 봐주셔서 감사합니다.

2024-02-09 05:22 UTC, sht02048 commented on util/sortCommonFrames.js
> +function sortCommonFrames(mainFrames, subOneFrames, subTwoFrames) {
민지님 해당 함수가 3개의 매개변수만을 특정해서 `filter`하는 과정이 포함되어있어 두 개의 매개변수만 받게 하려면 함수의 크기가 좀 커져야합니다. 그러기보단 필요시 새로운 함수를 만드는게 판단되어 우선 해당 함수의 이름을 `filterFramesByTwoSubs`로 변경하겠습니다!

2024-02-10 10:11 UTC, zzinLee commented on util/filterFramesByTwoSubs.js
> +  };
민석님! 해당 로직을 보니 반복되는 부분이 많은 것 같아 아래와 같이 변경해보았습니다.
혹시 제가 고려하지 못한 사항이 있을 것 같아서 제안 드리기는 조심스럽지만, 검토 부탁드립니다!
아래와 같이 진행하면 시간 복잡도를 많이 낮출 수 있을 것 같아서요 : ) 

제가 이해한 바로는 `main`영상의 원샷을 기준으로 
첫번째 서브영상에서 같은 프레임이 있고 두번째 서브 영상에서도 같은 프레임이 있다면 `doubleOverlappedFrames`로
첫번째 서브영상에서 같은 프레임이 있고 두번째 서브 영상에서는 같지 않다면 `subOneOverlappedFrames`로
첫번째 서브영상에서 프레임이 같지 않고 두번째 서브 영상에서는 같은 프레임이 있다면 `subTwoOverlapppedFrames`로
각각 push 해주는 작업입니다.

```js
function filterFramesByTwoSubs(mainFrames, subOneFrames, subTwoFrames) {
  const doubleOverlappedFrames = [];
  const subOneOverlappedFrames = [];
  const subTwoOverlappedFrames = [];
  
  mainFrames.forEach((frameNumber) => {
    const hasSubOneSameFrame = subOneFrames.includes(frameNumber);
    const hasSubTwoSameFrame = subTwoFrames.includes(frameNumber);
    
    if (hasSubOneSameFrame && hasSubTwoSameFrame) {
      doubleOverlappedFrames.push(frameNumber);
    } else if (hasSubOneSameFrame && !hasSubTwoSameFrame) {
      subOneOverlappedFrames.push(frameNumber);
    } else if (!hasSubOneSameFrame && hasSubTwoSameFrame) {
      subTwoOverlappedFrames.push(frameNumber);
    } 
  });
  
  return {
    doubleOverlappedFrames,
    subOneOverlappedFrames,
    subTwoOverlappedFrames,
  };
}

```

2024-02-10 10:42 UTC, zzinLee commented on services/convertFrameToBinaryArray.js
> +  const subTwoFramePath = path.join(__dirname, `../temp/difference/sub-two-contents/difference_${imageNumber}.jpg`);
제가 기존에 설정했던 paths 과 다른 부분이 있네요!
추후에 제가 수정해두겠습니다 :)

2024-02-10 10:48 UTC, zzinLee commented on services/convertFrameToBinaryArray.js
> +}
`Promise.all`을 사용하였군요! 저는 `Promise.allSettled`를 자주 사용하고 있습니다.
에러 핸들링 측면에서는 민석님께서 사용하신 Promise.all 이 좋을 것 같기도 한데,
pathList에 담긴 모든 배열에 대해 하나라도 에러가 발생한다면, 문제가 될 수도 있을 것 같아요.
이 연결과정에 대해 논의를 한 번 해볼 필요가 있을 것 같습니다! :)

2024-02-10 10:50 UTC, zzinLee requested changes
민석님! 전체적으로 코드가 가독성 좋게 작성되어 있어서 리뷰하기에는 매우 편했습니다.
filterFramesByTwoSubs.js 함수에 코드에 대한 코멘트를 남겼습니다.
검토부탁드리겠습니다 🙏

2024-02-10 15:20 UTC, sht02048 commented on util/filterFramesByTwoSubs.js
> +  };
수진님이 제안하신 코드가 훨씬 가독성도 좋고 시간복잡도 측면에서도 좋겠네요! 감사합니다!

2024-02-10 15:27 UTC, zzinLee commented on util/filterFramesByTwoSubs.js
> +  });
리뷰를 반영해주셨군요! 감사합니다 : ) 함수 작동에 문제가 없었다니 다행 이네요!

2024-02-10 15:28 UTC, zzinLee approved these changes
민석님 고생하셨어요~!

2024-02-10 15:32 UTC, alswla approved these changes
변경사항 모두 확인했습니다! 수고하셨습니다 민석님! 🔥

2024-02-10 15:34 UTC, merged