Feat. 메인영상 원샷지점 프레임 교체 지속시간 계산 기능 개발
KrossCutting/KrossCutting-server pull request #11
Opened 2024-02-08 17:10 UTC by alswla

# KanBan Title
- [메인영상 원샷지점 프레임 교체 지속시간 계산 로직 구현](https://www.notion.so/minsug/Server-compliations-POST-45553947a2ad4f1496ddf94c2248d848?pvs=4)

# Tasks in detail - checkList
- [x] 메인에서 [원샷으로 판단된 프레임 이미지](https://github.com/fab58d11a9b0471590c2486fe7cfff39?pvs=25)에 대해서 해당 원샷지점에서부터 프레임 교체 지속시간 추출 로직 구현
- [x] 메인에서 원샷으로 판단된 프레임에 대해 다음 원샷지점 사이의 프레임을 비교분석
- [x] 얼굴이 있는 구간은 편집이 들어가지 않도록 지속시간에 포함
- [x] 리턴값으로 프레임의 파일명 및 지속시간을 리턴

# Description
- 메인영상에서 원샷으로 도출된 지점에 대해서 해당 원샷이 끝나는 지점의 프레임을 확인합니다.
이를 통해 프레임 교체가 이루어질 구간(지속시간)을 확인할 수 있습니다.  

이때, 원샷이 끝나는 지점이란 해당 원샷이 끝나는 지점일 수도 있지만, 
곧바로 다른 얼굴이 인식될 경우 얼굴이 잘리거나 갑자기 얼굴이 나타나는 등 어색한 편집이 일어날 수 있으므로, 
원샷의 지속시간 외에도, 이후 일정 수준의 줌인된 얼굴이 나올 경우는 프레임 교체 지속시간에 포함하여 편집이 일어나지 않게 합니다.

원샷으로 판단된 프레임에서 이후 프레임들과 비교를 하면서 변화의 구간이 적다가 많아진다면, 원샷이 끝나는 지점으로 판단하고, 프레임 넘버와 지속시간을 리턴합니다.

# Concern
- 리뷰받고 싶은 부분 & 컨펌이 필요한 부분

# remarks
- 기타 특이 사항

# 주의 사항
- [] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [] 가장 최신 브랜치를 pull 하였습니다
- [] base 브랜치명을 확인하였습니다
- [] 코드 컨벤션을 모두 확인하였습니다
- [] 브랜치명을 확인하였습니다.
- [] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-09 04:24 UTC, sht02048 reviewed
민지님! 전반적으로 깔끔하게 코드를 작성하셔서 리뷰하기에 편했던 것 같습니다! 개인적인 의견으로 코멘트 하나 남겼습니다!

2024-02-09 04:24 UTC, sht02048 commented on services/analyzeDuration.js
> +      }
if else 문을 쓰는 것보다 if 문만 쓰는 방식은 어떻게 생각하시나요?!
```suggestion
      if (predictions.length < 1 && movementRatio <= MOVEMENT_THRESHOLD) {
        break;
      } 
      
       duration += 1;
```

2024-02-10 10:59 UTC, zzinLee commented on services/analyzeDuration.js
> +const mainFrameDirectory = path.join(__dirname, "../temp/frames/main-contents");
새로운 constants/path.js가 추가되어서 아래와 같이 변경하실 수 있을 겁니다!

```js
const { TEMP_DIR_FRAMES } = require("../constants/paths");
const mainFrameDirectory = path.join(TEMP_DIR_FRAMES.MAIN);
```

2024-02-10 11:03 UTC, zzinLee commented on services/analyzeDuration.js
> +    const nextFramePath = parseInt(path.basename(b).split("_").pop(), 10);
`path.basename()`을 통해서 현재 경로의 파일명만 받아올 수도 있네요 👍

2024-02-10 12:25 UTC, zzinLee commented on services/getSingleFaceFrames.js
>  }
`detectedFaceCountResults`로 detect된 Face의 결과값을 보내주시는 것 같네요.
함수명만 보고 얼굴의 갯수를 센 결과인 숫자를 반환하는 줄 알았는데 데이터도 함께 오는 것 같아요!
`detectedFaceResults` 로 보내주시면 조금 더 이해하기 편할 것 같습니다.

2024-02-10 12:30 UTC, zzinLee requested changes
민지님~ 파이프를 모두 연결하기 위해 
결과값을 모두 반환시켜주는 방식으로 변경 하시느라 고생많으셨어요!
리뷰 확인 부탁드릴게요!

2024-02-11 09:38 UTC, alswla commented on services/analyzeDuration.js
> +      }
민석님! 해당 부분 반영하도록 하겠습니다! if문 하나로 처리하는 것이 가독성이 좋아서 고민하던 부분이었는데 감사합니다👍

2024-02-11 09:41 UTC, alswla commented on services/analyzeDuration.js
> +const mainFrameDirectory = path.join(__dirname, "../temp/frames/main-contents");
수진님 감사합니다! merge 후 path 변경했습니다!👍

2024-02-13 10:37 UTC, sht02048 commented on services/analyzeDuration.js
> +const mainFrameDirectory = path.join(TEMP_DIR_FRAMES.MAIN);
민지님! `mainFrameDirectory`에 할당된 경로가 `TEMP_DIR_FRAMES.MAIN` 하나만 있어서 `path.join()` 쓰지않아도 될 것 같습니다!

2024-02-13 11:47 UTC, zzinLee commented on services/analyzeDuration.js
> +  const mainFrameFileList = await fs.readdir(TEMP_DIR_FRAMES);
민지님, 해당 변수는 아래와 같이 객체형태입니다. 
`TEMP_DIR_FRAMES.FOLDER` 로 사용해주셔요!

```js
const TEMP_DIR_FRAMES = {
  FOLDER: path.join(__dirname, "../temp/frames"),
  DIFF: path.join(__dirname, "../temp/frames/difference"),
  MAIN: path.join(__dirname, "../temp/frames/main-contents"),
  SUB_ONE: path.join(__dirname, "../temp/frames/sub-one-contents"),
  SUB_TWO: path.join(__dirname, "../temp/frames/sub-two-contents"),
};
```

2024-02-13 11:53 UTC, zzinLee commented on services/analyzeDuration.js
> +
`filteredFramePathList`가 fps 1 을 기준으로 연산하고 있기에 `findIndex` 를 통해,
원샷으로 잡힌 `singleShotPath` 경로와 같은 경우의 인덱스를 반환하여 사용해주시고 계시군요! 이해했습니다 ! ㅎㅎ

2024-02-13 12:05 UTC, sht02048 approved these changes

2024-02-13 12:18 UTC, zzinLee approved these changes
민지님 고생하셨습니다~!

2024-02-13 12:32 UTC, merged