Feat. 교체할 프레임에 대해 이미지 크기 변경 및 디졸브 효과 기능 개발
KrossCutting/KrossCutting-server pull request #13
Opened 2024-02-13 06:24 UTC by zzinLee

# KanBan Title
- [교체될 서브영상 구간에 대해 이미지 조정 및 교체 효과](https://www.notion.so/minsug/Server-compliations-POST-1-7c9ebe31eb8b4d5388ee624795a21052?pvs=4)

# Tasks in detail - checkList
- [x]  최종 확대 비율 연산 값 구하여 모든 프레임에 적용하기
- [x]  이웃하는 프레임에 일정 비율로 축소한 프레임을 연속적으로 덮어 씌우기
- [x]  원샷 진입 시효과를 주어 부드러운 전환(디졸브효과) 적용하기

# Description
- 해당 기능은 메인 영상을 기준으로, 변경되어야 하는 영상의 모든 프레임들의 위치를 재조정합니다.
- 주어진 `durationTime`이 종료되는 순간, 메인 영상 프레임이 다시 재생된다는 전제하에 진행합니다. (이는 추후 칸반에서 진행)
- 위치가 재조정된 영상 중, 일부 프레임을 변경하여 디졸브 효과(2개의 영상 합성 효과)를 주도록 합니다.
- 교차 편집 영상 간의 편집이 자연스럽게 보이도록 하기 위하여 필요한 작업입니다.

# Concern
- 현재 병렬적인 기능 작업을 진행하고 있으므로 인자의 값 변경이 있을 수 있습니다.

# remarks
- `services` 폴더에 파일이 1개 변경 되었습니다
: 기존 PR에 기능개발 했었던 `services/resizeFrames.js` 파일을 삭제하고
`services/crossCuttingFrames.js` 로 이름과 내용을 변경하였습니다.
- `util` 폴더에 파일이 2개 추가 되었습니다 : `util/parseImgPath.js`와 `util/stringifyImgPath.js`
- `services` 폴더에 파일이 2개 추가 되었습니다 :  `dissolveFrames.js`와 `resizeAndDissolve.js`

### `util/parseImgPath.js`
- 이미지 파일 경로를 받아 프레임넘버와 현재 사용하는 비디오 종류를 알아낼 수 있습니다.

### `util/stringifyImgPath.js`
- 프레임 넘버와 비디오 종류로 올바른 이미지 파일 경로를 생성합니다.

### `services/crossCuttingFrames.js`
- `detectFace`함수 반환값에 의존합니다.
- `resizeAndDissolve` 함수를 마지막에 호출합니다.
- 해당 파일의 메인 함수는 `crossCuttingFrames` 함수입니다.  
-**`crossCuttingFrames` 함수**
인자1 | `mainImg` (교차 편집 대상인 메인 이미지 경로 <string>)
인자2 | `subImg` (교차 편집 대상인 서브 이미지 경로 <string>)
인자3 | `durationTime` (초 <number>)  
반환값 | null

- `cutFrameArguments` 함수 
위에서 실행한 메인함수에 의해 얼굴 좌표 값을 전달 받은 후,
이를 연산하여 프레임을 자를 수 있는 인수를 구하여 반환합니다. 
이를 추후 여러 프레임에 재 사용합니다.

- `isSamePositionFace` 함수
두 프레임에서 인지한 얼굴의 위치가 일치한다면 true를 반환하는 함수입니다.
두 프레임에서 인지한 얼굴 위치가 상이하다면 false를 반환합니다.
이는 사전 작업에서 예외케이스 제외 시, 삭제 가능성이 있는 함수입니다. 

### `services/dissolveFrames.js`
이전 프레임과 현재 프레임의 경로를 입력받습니다.
이전 프레임의 채도/명도를 낮춘 후 현재 프레임의 투명도를 조절하여 덧입힘으로써
합성된 이미지를 생성한 후 기존 경로에 덮어씌웁니다.

### `services/resizeAndDissolve.js`
변경해야 하는 모든 프레임에 대해 `cutFrameArguments`의 반환값을 이용하여,
리사이징 작업을 거칩니다.
시작하는 프레임 3개에 대해서만 디졸브 효과를 줍니다.
이 모든 작업을 순차적으로 진행하는 함수입니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-13 09:58 UTC, alswla requested changes
수고하셨습니다 수진님! 개인적인 의견으로는 if문 분기처리도 통일하여 처리되면 좋겠다는 의견 추가로 드립니다! (이전 파일이라 코멘트가 안달리네요 😢) 그 외 마이너한 코멘트도 확인해주시면 감사하겠습니다! 

추가로 파일명은 논의한대로 `edit.controller.js`, `applyDissolve.js`, `editFrames.js`로 변경 부탁드리겠습니다! 🙇‍♀️

2024-02-13 09:58 UTC, alswla commented on services/crossCuttingFrames.js
> +      subFaceCoord,
수진님! 위의 [`mainFaceCoored`, `subFaceCoord`](https://github.com/KrossCutting/KrossCutting-server/pull/13/files#diff-3d785b0ecae6745eff5cfedc03050330aad703811aa4d3ae6c78770ad0b20204L129-L130) 변수명의 경우에 프레임 조정에 필요한 얼굴인 것으로 보입니다! 변수명을 `mainFaceTarget` 혹은 `targetMainFace`, `subFaceTarget`, `targetsubFace`로 변경해도 좋을 것 같다는 의견입니다! :)

2024-02-13 09:58 UTC, alswla commented on services/crossCuttingFrames.js
>  function cutFrameArguments(mainCoord, subCoord, imgMetadata) {
수진님! 아래 변수명 변경 코멘트에 따라 매개변수명도 변경하면 좋을 것 같습니다 :) (`mainTarget`, `subTarget` 등)

2024-02-13 09:58 UTC, alswla commented on services/crossCuttingFrames.js
> +        const imgBuffer = await sharp(subImg)
수진님! 함수 자체가 frame을 쓰고 있고 프레임이미지이므로 img 변수를 frame으로 통일해도 좋을 것 같다는 의견입니다 :)

2024-02-13 09:58 UTC, alswla commented on services/resizeAndDissolve.js
> +  await Promise.allSettled(resizePromiseList);
수진님! 이 경우에는 교체할 프레임들에 대한 처리를 해주고 있는 부분이라 한 장도 빠짐없이 성공해야하므로 Promise.all의 사용도 좋을 것 같다는 의견입니다! 🤔

추가로 allSettled를 사용할 경우에는, 이미지 리사이즈의 일부가 실패할 경우를 대비하여 fulfilled의 경우에만 사용하고 rejected일 경우에는 사이즈 처리를 다시 진행 하거나 혹은 rejected이후로는 사이즈 조절을 하지 않는 등의 처리가 진행되면 좋을 것 같습니다 👍 (에러핸들링 칸반때 같이 진행하면 좋을 것 같습니다😉)

2024-02-13 09:58 UTC, alswla commented on services/crossCuttingFrames.js
>        }
수진님 `fs.promises`로 변경해 처리해주셨군요! 👍 `const imgBuffer = await sharp(subImg)`에서의 `await`은 `.toBuffer()`가 프로미스를 반환할 경우에만 외부 비동기 작업의 완료를 기다리게 될 것 같습니다! 

즉, 이전 코드에서는 `toBuffer()`내부에 `fs.writeFile()`라는 또다른 비동기 작업을 호출해주고 있었는데 이에 대해선 `imgBuffer`의 `await`이` fs.writeFile()`의 비동기작업까지 기다려주지 못해서 `undefined`를 반환했을 것 같습니다! 

해당 문제에 대해서 `sharp` 처리와 `fs.writeFile` 작업의 완료를 각각 `await`을 통해 기다려주는 방식으로 깔끔하게 잘 해결해주신 것 같습니다 🔥👍

2024-02-13 12:32 UTC, zzinLee commented on services/resizeAndDissolve.js
> +  await Promise.allSettled(resizePromiseList);
확인했습니다 민지님~! 저도 같은 의견입니다. Promise.all 로 변경해 두겠습니다.

2024-02-13 12:33 UTC, zzinLee commented on services/crossCuttingFrames.js
> +        const imgBuffer = await sharp(subImg)
민지님~! `imgBuffer` 는 임시로 이미지 버퍼를 사용하는 것이므로,일부러 코드의 컨텍스트와 관련없는

2024-02-13 12:35 UTC, zzinLee commented on services/crossCuttingFrames.js
>  function cutFrameArguments(mainCoord, subCoord, imgMetadata) {
해당 부분의 변수명은 조금 더 고민해보겠습니다!

2024-02-13 15:38 UTC, sht02048 reviewed
수진님 이미지 위치를 조정하고 특정 효과를 주는 작업이 어려우셨을텐데 잘 해주셨네요! 수고많으셨습니다!

2024-02-13 15:38 UTC, sht02048 commented on services/resizeAndDissolve.js
> +async function resizeAndDissolve(
수진님! resizeAndDissolve라는 함수 이름은 하나의 함수에서 두 가지 기능을 수행하는 명시하는 것 같은데 실제로는 resize된 frame을 dissolve 함수로 전달하는 것 같습니다! 함수명을 조금 더 순수하게 변경하는 것은 어떻게 생각하시나요? - 마땅히 떠오르는 함수 이름은 없긴 하네요... 정 없으면 일단 진행하시죠!
ex) `makeResizedFrameDissolve`

2024-02-13 15:38 UTC, sht02048 commented on util/stringifyImgPath.js
> +  let imgPathResult;
수진님 `imagePathResult`에 아무런 값이 할당되어있지않아도 괜찮지만 어떤 타입의 값이 들어올 거라는 의미에서 빈 문자열을 할당해주는 건 어떨까요?

2024-02-14 13:06 UTC, alswla submitted a review, later dismissed
수진님 어려운 작업이셨을텐데 정말 수고 많으셨습니다!🔥

2024-02-14 13:25 UTC, alswla commented on src/services/editFrames.js
> +      !mainFaceData.predictions.length || !subFaceData.predictions.length;
undefined 오류 원인 확인 후 조건문 정리 해주셨군요 👍

2024-02-14 13:26 UTC, alswla approved these changes, later dismissed
수진님! 파일명이나 변경된 부분 모두 확인했습니다! 다른 파일들까지 같이 신경써서 수정해주셔서 감사합니다! 🙇‍♀️ 수고하셨습니다!

2024-02-14 15:11 UTC, sht02048 reviewed
수진님 어려운 로직 구상하시고 구현하시느라 고생많으셨어요! 사소한 코멘트 하나 남겼는데 확인 부탁드려요~

2024-02-14 15:11 UTC, sht02048 commented on src/services/replaceFrames.js
> +  const transferFramePromiseList = transferFrameList.map(
여기에 인덴팅이 하나 있으면 읽기에 더 편할 것 같습니다  수진님!

2024-02-14 17:06 UTC, zzinLee commented on services/crossCuttingFrames.js
> +      subFaceCoord,
개인적으로는 얼굴좌표 (Coordinate) 가 좀 더 이해하기 좋아서 해당 변수명을 유지하고 있습니다!
x,y 값을 담는 숫자이므로 좌표와 관련한 변수명이 더 좋을 것 같아서, 해당 변수명은 조금 더 고민해보겠습니다!

2024-02-14 17:22 UTC, zzinLee commented on src/services/replaceFrames.js
> +  const transferFramePromiseList = transferFrameList.map(
반영하였습니다 민석님!

2024-02-15 02:02 UTC, zzinLee commented on util/stringifyImgPath.js
> +  let imgPathResult;
해당 내용 확인하고, let 변수를 쓰는 대신 return 문으로 바로 값을 반환하도록 변경하였습니다~!
감사합니다 민석님!

2024-02-15 02:02 UTC, sht02048 submitted a review, later dismissed
변경사항 모두 확인했습니다! 수고하셨어요 수진님~

2024-02-15 03:19 UTC, sht02048 approved these changes

2024-02-15 03:19 UTC, alswla approved these changes
수진님 모두 확인했습니다! 수고하셨습니다! 🔥

2024-02-15 03:20 UTC, merged