Feat. 파일 업로드 엔드 포인트 및 비즈니스 로직 작성
KrossCutting/KrossCutting-server pull request #15
Opened 2024-02-13 09:55 UTC by sht02048

# KanBan Title
- [파일 업로드 엔드 포인트 및 비즈니스 로직 작성](https://minsug.notion.site/Server-multer-65b4c55525aa4b9080e901051091d9d6?pvs=4)

# Tasks in detail - checkList
- [x]  파일 업로드 엔드 포인트 생성
- [x]  로컬 파일 저장 함수 생성
- [x]  mp3 및 wav 파일 추출 후 로컬 저장
- [x]  로컬에 저장된 비디오 및 오디오(mp3) 파일 s3에 업로드
- [x]  upload 컨트롤러 함수 생성

# Description
Kross-cutting 사용 방식을 url 입력으로 한정지었지만 영상 다운로드 시간이 오래 걸림에 따라 사용자 경험 만족도가 떨어질 것에 대비하여 시간을 짧게 단축할 수 있는 파일 업로드 방식을 도입했습니다. 

유저가 비디오 파일을 업로드하면 오디오 파일을 추출한 후 비디오와 오디오를 모두 S3에 저장하고 클라이언트에게 S3에 접근할 수 있는 `singedUrl`을 전달합니다.

# remarks
- multer 설치했습니다. - _npm install 필요_

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-13 10:44 UTC, alswla requested changes

2024-02-13 10:44 UTC, alswla commented on loaders/routes.js
> +  app.use("/videos", compilations);
민석님! 이렇게 /videos에다가 contents, compilations를 연결해놓게 된다면 두 라우터가 동일한 경로를 공유하게 되므로 요청이 들어왔을 때 어떤 라우터가 처리할지 명확하지 않을 것 같습니다.

특히 express는 등록된 순서대로 미들웨어와 라우트 핸들러를 실행하므로, 
첫 번째로 등록된 contents 라우터만 작동하고 compilations 라우터는 도달할 수 없는 코드가 될 것 같아, 
아래와 같이 수정 부탁드립니다! 🙇‍♀️

```suggestion
  app.use("/videos/contents", contents);
  app.use("/videos/compilations", compilations);
```

2024-02-13 10:44 UTC, alswla commented on routes/contents.js
> +router.post("/contents/urls", transferController.transferMedia);
위에서 라우터 경로 설정에 대해 드린 코멘트의 변경 적용사항에 따라 아래와 같이 contents 라우터 내 경로 설정도 아래와 같이 변경 부탁드립니다! 🙇‍♀️

```suggestion
router.post(
  "/files",
  uploadToLocal.fields([
    { name: "mainVideoFile" },
    { name: "subOneVideoFile" },
    { name: "subTwoVideoFile" },
  ]),
  upload,
);

router.post("/urls", transferController.transferMedia);
```

2024-02-13 10:44 UTC, alswla commented on routes/controllers/upload.controller.js
> +        );
들어온 모든 파일에 대해서 성공해야하기 때문에 Promise.all의 사용도 고려할 수 있을 것이라는 의견입니다! 🤔 에러핸들링 칸반 작업시 해당 부분도 같이 논의해보면 좋을 것 같습니다!

2024-02-13 10:44 UTC, alswla commented on routes/contents.js
> +const upload = require("./controllers/upload.controller");
컨트롤러라는 것을 알 수 있게 `uploadController`라는 변수명이 더 좋을 것 같다는 의견입니다!

2024-02-13 10:44 UTC, alswla commented on routes/controllers/upload.controller.js
> +    res.status(200).send({
저희가 S3 Client url을 반환할때 상태코드를 200을 쓰고 있었는데 전체적으로 201의 사용이 더 적절한 것 같다는 의견입니다!🤔 업로드 요청시 클라이언트에서 보낸 POST 요청에 따라 응답을 보내는 것이기 때문에 201로 전체적으로 변경하면 좋을 것 같다는 의견입니다! (transfer.controller.js 도 동일하게 변경)

참고: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2024-02-13 10:44 UTC, alswla commented on services/uploadToLocal.js
> +          throw new Error(`Unknown fileName: ${file.fieldname}`);
switch문을 통한 path 설정 좋은 것 같습니다 👍

2024-02-13 10:51 UTC, sht02048 commented on loaders/routes.js
> +  app.use("/videos", compilations);
민지님 확인했습니다! 두 라우트 모두 `"/videos"`에 대한 요청으로 `compilations`는 절대 발동될 수 없겠네요.. 꼼꼼히 봐주셔서 감사합니다!

2024-02-13 10:54 UTC, sht02048 commented on routes/controllers/upload.controller.js
> +        );
넵넵! 에러 처리하기 위해 `Promise.all`을 사용했는데 아무래도 에러 핸들링하기에는 `allSettled`보다는 `all`이 더 편리하더라구요. 스크럼 회의때 수진님하고 이야기 한번 해보면 좋을 것 같습니다!

2024-02-13 10:55 UTC, sht02048 commented on routes/contents.js
> +const upload = require("./controllers/upload.controller");
오 넵! 좋습니다!

2024-02-13 10:55 UTC, sht02048 commented on routes/controllers/upload.controller.js
> +    res.status(200).send({
넵 좋습니다! 반영하겠습니다~

2024-02-13 10:59 UTC, zzinLee commented on services/uploadToLocal.js
> +      }
```suggestion
      switch (file.fieldname) {
        case "mainVideoFile":
          fileName = "main-video";
          break;
          
        case "subOneVideoFile":
          fileName = "sub-one-video";
          break;
          
        case "subTwoVideoFile":
          fileName = "sub-two-video";
          break;
          
        default:
          throw new Error(`Unknown fileName: ${file.fieldname}`);
      }
```
switch 의 case 문에는 개행을 해주시는 것이 좋을 것 같아요 !

2024-02-13 10:59 UTC, zzinLee commented on services/uploadToLocal.js
> +      done(null, fileName + ext);
```suggestion
      const ext = path.extname(file.originalname);
      
      done(null, fileName + ext);
```
할당문과 실행문사이에는 개행이 있으면 더 좋을 것 같아요~!

2024-02-13 11:02 UTC, zzinLee approved these changes, later dismissed
민석님 고생하셨습니다!
사소하게 개행 부분에서 문제가 있어 리뷰 남겼습니다 :)
확인 부탁드릴게요!

2024-02-13 12:53 UTC, zzinLee commented on routes/controllers/upload.controller.js
> +        );
저 역시도 모든 작업에 대해 실행이 진행되어야 되는 경우라면
Promise.allSettled 보다는 Promise.all이 더 좋을 것 같다는 의견입니다.

2024-02-13 13:44 UTC, zzinLee approved these changes, later dismissed
multer 적용하시느라 고생많으셨습니다! :)

2024-02-13 18:45 UTC, alswla requested changes

2024-02-13 18:45 UTC, alswla commented on routes/contents.js
> +const upload = require("./controllers/upload.controller");
uploadController는 함수 하나만 export되기 때문에 uploadController로도 괜찮을 것 같다는 생각입니다!

2024-02-14 01:50 UTC, alswla approved these changes
수정사항 확인했습니다 민석님! 수고하셨습니다! 🔥

2024-02-14 02:01 UTC, zzinLee approved these changes

2024-02-14 02:05 UTC, merged