Feat. 프레임 판별 로직
KrossCutting/KrossCutting-server pull request #19
Opened 2024-02-15 06:40 UTC by sht02048

# KanBan Title
- [컨트롤러 연동](https://minsug.notion.site/Server-751ffa1efe8444a68fee545c19231a21?pvs=4)

# Tasks in detail - checkList
- [x] 일치율 분석과 전처리를 담당하는 함수 생성 

# Description
-  subOne과 subTwo에서 모두 원샷으로 판별된 프레임에 한해서 일치율이 더 높은 프레임을 판별합니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-15 11:49 UTC, zzinLee commented on src/services/sortFrames.js
> +  );
labels 가 `Object.keys(singleShots)`의 값이라 singleShots의 key값들만 담은 배열이 반환되는 듯 합니다.
여기에서 singleShots 의 key값으로 labels[1], labels[2]를 주고 계신데요!
```js
const [ 변수명1, 변수명2, 변수명3 ] = labels;
```
위와 같이 변수명으로 담아 변경해주시면 더욱 가독성이 높아질 것 같아요!

2024-02-15 12:00 UTC, zzinLee requested changes
확인부탁드립니다~!

2024-02-16 11:18 UTC, alswla approved these changes, later dismissed
미들웨어 2개 분리하시느라 수고하셨습니다 민석님!🙇‍♀️ mergeFrames 함수 관련해서는 스크럼시 논의해보면 좋을 것 같습니다 👍

2024-02-16 11:18 UTC, alswla commented on src/util/getBlackPercent.js
> +module.exports = getBlackPercent;
민석님! 스크럼시 논의한 것처럼 해당 함수로 일치율을 비교하신 후에 너무 많은 교체구간이 하나의 영상으로 치우칠 경우에 적절히 섞어주는 식의 함수를 추가해보면 좋을 것 같습니다 👍

2024-02-16 11:18 UTC, alswla commented on src/util/mergeFrames.js
민석님! 연속된 프레임에 대해 지속시간을 합쳐주는 함수를 저도 별도로 리사이즈 상황(디졸브효과 유무)에 따라 2가지로 나눈 로직이 있어서 스크럼시 논의하여 사용을 결정하면 좋을 것 같습니다!👍

추가로 실제 사용한 곳을 보니 subOneMergedFrames, subTwoMergedFrames에 대해 별도로 해당 함수를 사용하고 있어 각 프레임의 지속시간을 합칠 경우 겹치는 구간이 생길 수 있을 것 같다는 의견입니다!

2024-02-16 11:18 UTC, alswla commented on src/middlewares/adjustAudio.js
> +      labelInfo[videoLabel] = startTime + videoTimes[index];
사용자가 선택한 구간에 조정된 시간을 더해서 최종 프레임 추출 구간을 구해주시는군요 👍

2024-02-17 03:20 UTC, alswla approved these changes, later dismissed
수고하셨습니다 민석님! 🔥

2024-02-18 05:52 UTC, alswla approved these changes
변경사항 모두 확인했습니다!

2024-02-18 05:53 UTC, zzinLee approved these changes
민석님 확인했습니다~!

2024-02-18 05:57 UTC, merged