Feat. validation 앤드 포인트 생성
KrossCutting/KrossCutting-server pull request #22
Opened 2024-02-18 17:18 UTC by sht02048

# KanBan Title
- task card 링크

# Tasks in detail - checkList
- [x] compilations 라우터에서 adjustAudio 제거
- [x] validations 라우터 생성 및 adjustAudio 배치
- [x] 클라이언트에 완성된 영상의 s3 url 전달
- [x] 미들웨어 지날때 필요없는 리소스 삭제   

# Description
- 유저에게 진척상황을 알리기 위해 엔드포인트를 분리하였습니다.  기존에는 하나의 앤드포인트에서 오디오 유효성 검사부터 최종 영상까지 작업했지만 이제 validation이라는 엔드포인트를 통해 유효성 검사 후 편집을 시작합니다.
- 유저에게 완성된 영상을 다운로드 받을 수 있게 인가된 s3 url을 전달합니다. 

# remarks
- 미들웨어 작업이 끝날때 필요없는 리소스를 지워주는 코드를 작성했으나 개발 중에는 필요없어 주석처리 해놓았습니다. 추후 배포할때 주석해제필요합니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-18 18:28 UTC, alswla requested changes
민석님 오디오 유효성 분리하시고 다운로드 기능 구현하시느라 수고하셨습니다! 몇가지 코멘트들이 있어서 확인 부탁드리겠습니다! 🙇‍♀️

2024-02-18 18:28 UTC, alswla commented on src/controllers/crossCutting.controller.js
> +    s3ClientFinalVideoUrl,
바로 메세지에 완료된 영상의 Client Url 보내주시는군요! 다만 클라이언트 측에서 받아쓰기 용이하도록 프로퍼티값을 주면 좋을 것 같다는 의견입니다! 

```suggestion
    message: s3ClientFinalVideoUrl,
    // 혹은 finalVideo: s3ClientFinalVideoUrl
```

2024-02-18 18:28 UTC, alswla commented on src/middlewares/adjustAudio.js
> +const START_POINT = require("../constants/startPoints");
상수 import문은 가장 아래로 내려주시는 것이 통일성이 좋을 것 같다는 개인적인 의견입니다! 🤔

2024-02-18 18:28 UTC, alswla commented on src/services/extractStartTime.js
> +      }
이후 에러 핸들링 처리를 위해 try catch문으로 변경해주셨군요!👍

2024-02-18 18:28 UTC, alswla commented on src/services/getFinalVideoUrl.js
> +const { TEMP_DIR_VIDEOS } = require("../constants/paths");
동일한 코멘트로 상수 import는 가장 아래로 내려주시는게 통일성 있을 것 같습니다!

2024-02-19 08:21 UTC, zzinLee approved these changes, later dismissed
민석님~ 리팩터링 된 코드들 모두 확인하였습니다!

2024-02-20 03:04 UTC, alswla approved these changes
변경사항 모두 확인했습니다! 수고하셨습니다!

2024-02-20 03:21 UTC, zzinLee commented on src/controllers/crossCutting.controller.js
> +    s3ClientFinalVideoUrl,
리소스 파일 생성에 따라 status code를 세심하게 신경써주셨네요 :) 확인하였습니다!

2024-02-20 03:21 UTC, zzinLee approved these changes

2024-02-22 10:23 UTC, merged