Refactor: crossCutting 컨트롤러 병합
KrossCutting/KrossCutting-server pull request #25
Opened 2024-02-25 14:08 UTC by sht02048

# KanBan Title
- [[server] 앱 전용 앤드포인트 및 미들웨어 생성](https://minsug.notion.site/server-1944482a211d45f79bbfa60cdd1a8e0c?pvs=4)

# Description
- 나뉘어져있던 crossCutting 컨트롤러를 하나로 병합했습니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-25 15:12 UTC, zzinLee commented on src/services/assignEditPoints.js
> +  return { subOneMergedFrames, subTwoMergedFrames };
리사이징에서 나던 프레임 중복 오류를 잡아주셨네요 :) 감사합니다!

2024-02-25 15:21 UTC, zzinLee approved these changes
민석님.. 고생하셨습니다..우선 전부 확인 했어요!
3개 아닌 2개 영상 선택 시 관련사항과 필요한 로직을 합치는 것 꼭 같이 해요.

2024-02-25 15:25 UTC, zzinLee commented on src/controllers/crossCutting.controller.js
> +      : assignEditPoints(editPoints, selectedEditPoints);
편집점이 없으면 sortFrames를 있다면 assignEditPoints로직을 통해서 app 로직과 웹 로직을 분리해주셨군요.
selectedEditPoints가 정의되었는지, 정의되지 않았는지 확인하고 있기때문에 꼭 undefined를 쓰지 않고도 처리는 가능할 것 같습니다!
```suggestion
  const { subOneMergedFrames, subTwoMergedFrames } =
    selectedEditPoints
    ? assignEditPoints(editPoints, selectedEditPoints)
    : await sortFrames(singleShots, editPoints);
```

2024-02-25 15:25 UTC, zzinLee approved these changes, later dismissed

2024-02-25 16:21 UTC, alswla requested changes
민석님 수고하셨습니다!!! 코멘트 확인 부탁드립니다!

2024-02-25 16:21 UTC, alswla commented on src/controllers/crossCutting.controller.js
> +const assignEditPoints = require("../services/assignEditPoints");
아래와 같이 순서 변경해주시면 좋을 것 같아요!

```suggestion
const getFinalVideoUrl = require("../services/getFinalVideoUrl");
const assignEditPoints = require("../services/assignEditPoints");
const progressStatus = require("../routes/progressStatus");
const { TEMP_DIR_FRAMES, TEMP_DIR } = require("../constants/paths");
```

2024-02-25 16:21 UTC, alswla commented on src/controllers/crossCutting.controller.js
> +      : assignEditPoints(editPoints, selectedEditPoints);
`selectedEditPoints` 즉, 선택된 편집점이 없을 경우 값이 반드시 `undefined`로 온다면 경우라면 확실하게 명시하여 확인하는 것도 좋을 것 같다는 의견입니다! 다만 현재 app 클라이언트 코드를 확인해보니 `editPoints`가 선택되지 않을 경우 `undefined`를 반환하는지 여부에 대해서는 한번 더 확인 부탁드립니다! (빈 배열로 오는 것 같은데 확인 부탁드립니다!🙇‍♀️)

(만약 빈 배열로 오고 이를 처리해야한다면 제가 추후 진행할 리팩토링시 진행해보겠습니다!)

2024-02-26 04:49 UTC, sht02048 commented on src/controllers/crossCutting.controller.js
> +      : assignEditPoints(editPoints, selectedEditPoints);
`selectedEditPoints`가 없다면 키는 있으나 값이 빈 배열입니다. 빈 배열일 경우라도 로직이 정상작동해서 이대로 유지하겠습니다!

2024-02-26 05:17 UTC, alswla approved these changes
수고하셨습니다 민석님!! 👍

2024-02-26 06:26 UTC, zzinLee approved these changes

2024-02-26 06:27 UTC, merged