Refactor. 미디어파일 트랜스러 기능 리팩토링
KrossCutting/KrossCutting-server pull request #3
Opened 2024-02-03 10:48 UTC by alswla

# KanBan Title
- [[Server] contents POST 리소스 파일 - 전달받은 url로 파일 다운로드&업로드](https://www.notion.so/minsug/Server-contents-POST-url-s3-9a46ec1aaa2a436c92224e7301e3f672?pvs=4)

# Tasks in detail - checkList
- [x] AWS S3 인스턴스 생성
- [x] 사용자로부터 전달받은 url로 영상 및 오디오 다운로드
- [x] 영상 및 오디오 유효성 검사
- [x] 다운받은 영상 및 오디오 포맷 변경
- [x] 영상 및 오디오 S3 업로드
- [x] 클라이언트에게 s3ClientUrl 전달 

# Description
-  AWS S3에 업로드된 영상 및 오디오 파일의 길이가 맞지 않고 오디오 소리에 이상이 있어 해당 부분 수정하였습니다.
   추가로 오디오 파일과 영상의 경우 사용시에만 변환을 하고 가공하는 것이 효율적일 것이라는 논의 결과에 따라
   포맷 변경 파일은 삭제하였고, 이후 유틸함수로 별도 생성 예정입니다.

# remarks
- 포맷 확인 유틸 함수 생성이 이후 작업시 필요할 수 있습니다.
- 포맷 확인 여부에 따른 포맷 변경 유틸 함수 생성이 필요할 수 있습니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다. (권장)
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-03 13:10 UTC, sht02048 approved these changes
미디어 파일 트랜스퍼 기능에서 확장자 변환 로직 삭제 확인했습니다. 감사합니다!

2024-02-03 13:14 UTC, zzinLee commented on services/getMediaResources.js
> +        ContentType: "video/mp4",
민지님 ContentType 디버깅 하느라 수고많으셨습니다.
변경사항 확인하였습니다!

2024-02-03 13:17 UTC, sht02048 requested changes

2024-02-03 13:17 UTC, sht02048 commented on services/getMediaResources.js
> +        ContentType: "video/mp4",
민지님 이제 확장자가 `mp4` 혹은 `webm`일 수 있어서 key를 가변적으로 주거나 통일해야할 것 같습니다!

2024-02-03 13:54 UTC, alswla commented on services/getMediaResources.js
> +        ContentType: "video/mp4",
확인 감사합니다 민석님! 지금 수정해서 다시 올렸습니다 🙇‍♀️

2024-02-03 16:09 UTC, zzinLee commented on services/getMediaResources.js
> +        : `${folder}/videos/${title}-original.webm`;
삼항연산자로 깔끔하게 분기처리 👍 좋습니다! 변경사항 확인하였습니다.

2024-02-04 02:10 UTC, zzinLee submitted a review, later dismissed
민지님 변경사항 모두 확인하였습니다.

2024-02-04 05:54 UTC, sht02048 approved these changes
변경 사항 확인했습니다~ 수고하셨어요!

2024-02-04 05:55 UTC, zzinLee approved these changes
민지님 확인했습니다!

2024-02-04 06:43 UTC, merged