Feat. 비디오에서 프레임 추출 기능 개발
KrossCutting/KrossCutting-server pull request #5
Opened 2024-02-03 16:04 UTC by zzinLee

# KanBan Title
- [[Server]  compliations POST 영상 프레임 추출 구현](https://www.notion.so/minsug/Server-compliations-POST-784fa445e460481091bbbb0ad6a4b9a6?pvs=4)

# Tasks in detail - checkList
- [x]  사용자로부터 입력받은 시작점을 옵션으로 하여, 영상을 *30fps/1fps* 프레임 추출합니다.
- [x]  우선 중심이 되는 메인 영상, 서브 영상 2개를 받아왔다는 전제 하에 1fps를 추출하도록 작성
- [x]  프레임 추출이 완료시 각 영상에 맞는 폴더에 업로드 완료
- [x]  메인 영상 1개에 대하여 시작점(`start time`)부터 30fps로 프레임을 추출
- [ ]  30fps로 추출하는 과정에서 1fps에 해당하는 프레임 이미지들을 별도로 키값을 설정해 업로드 
⇒ 이는 추후 [이어지는 칸반](https://www.notion.so/Server-compliations-POST-fab58d11a9b0471590c2486fe7cfff39?pvs=21)에서 작업할 예정입니다.

# Description
메인 영상에 대해 기본 프레임(30fps) 및 비교 분석용 프레임(1fps)을 추출하는 작업입니다.
30fps 프레임은 영상 편집 및 합성, 1fps는 영상 편집구간을 설정하기 위한 비교분석 알고리즘의 수행의 용도를 위해 추출합니다.

영상을 분석 후 합성하는 과정에 있어서 
1. 직접 `ffmpeg` 로 영상을 편집하는 방법과 
2. `ffmpeg`로 프레임 즉 이미지를 동영상으로 편집하는 과정을 비교해보고,
두번째 선택안인 프레임(이미지)합성의 속도가 더욱 빠른 것을 확인한 후 해당 작업을 진행하였습니다.

해당 과정에서는 프레임을 추출할 영상의 경로와 추출한 프레임을 넣어 줄 경로를 매개변수로 받고,
추출할 프레임 값을 함수도 매개변수로 지정할 수 있도록 하였습니다.

현재는 모든 요소에 대해 1fps로 추출하도록 지정한 상태이나
추후 필요에 따라 main 영상의 30fps가 필요하다면 
`req.body.videoUrls`객체의 key 값을 확인하여 매개변수 `fps`를 30으로 전달,
서브 영상의 1fps가 필요하다면 key 값을 확인하여 매개변수 `fps`를 1로 전달하여 
원하는 경로로 추출하도록 합니다.

# Concern
기존의 Key값 네이밍 컨벤션은 아래와 같았으나 
_ex. mainVideo_30fps_0030 , mainVideo_1fps_0030_
1fps 추가 추출 과정 없이 진행할 예정이며 비디오는 경로가 지정 되므로
편의를 위해 파일명에 명명하지 않았습니다.

# remarks
- 칸반링크에 req.body로 쓸만한 mock data를 추가해두었고 주석으로 토글할 수 있도록 해두었습니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-03 16:22 UTC, sht02048 requested changes

2024-02-03 16:22 UTC, sht02048 commented on routes/controllers/videoFrame.controller.js
> +      `videos/${convertPath(folderPath)}/${filePath}`,
[`tempDirectory`](https://github.com/KrossCutting/KrossCutting-server/pull/5/files#diff-7fadd2bb44312aaf8f0ac4c253c16aee05a945775c7b36e40524fe56dbba99bdR8)에서 쓰인 절대경로와 달리 이 경로는 상대 경로처럼 보이는데 __dirname을 이용해서 절대경로를 명시적으로 할당해주는 것은 어떨까요? 현재는 문제가 없을 수 있지만 추후 배포될 시 에러가 발생하는 원인이 될 수도 있을 것 같습니다!

2024-02-04 07:03 UTC, alswla requested changes

2024-02-04 07:03 UTC, alswla commented on routes/controllers/videoFrame.controller.js
> +      `videos/${convertPath(folderPath)}/${filePath}`,
@sht02048 민석님! ` const tempDirectory = path.join(__dirname, "../../temp");` 에서 절대경로를 정해주고, 동적으로 변하는 경로에 대해 path.join을 통해 경로를 이어붙이고 있어 문제가 없을 것으로 보입니다! :)

2024-02-04 07:03 UTC, alswla commented on routes/controllers/videoFrame.controller.js
> +  const startPointsList = Object.values(req.body.startPoints);
수진님! 이건 제 개인적인 의견이라 참고만 부탁드립니다! :) 

List 자체가 video Path 전체에 대한 리스트 즉, 나열이라고 생각하여 아래와 같은 변수명도 좋을 것 같습니다.
동일한 맥락으로 `startPoint`도 이미 List이므로 `startPointList`도 좋을 것 같다는 의견입니다!

```suggestion
  const videoPathList = Object.entries(req.body.videoUrlList);
  const startPointList = Object.values(req.body.startPoints);
```

2024-02-04 07:03 UTC, alswla commented on services/extractFramesFromVideo.js
> +  ]);
수진님! 프레임 추출 관련 코드 깔끔하게 정리 잘 되어 있는 것 같습니다! 수고하셨습니다 👍

다만 현재는 필요하지 않지만, 이후 서브영상의 경우 일정 구간에 대해서 30fps로 별도 추출이 필요한 작업이 있으므로 (영상 교체를 위함) duration 옵션을 추후에 리팩토링시 추가하면 될 것 같습니다! 노션에 TODO로 이후 작업이 필요한 부분으로만 마크해주시면 될 것 같습니다! 🫡

2024-02-04 07:25 UTC, zzinLee commented on routes/controllers/videoFrame.controller.js
> +      `videos/${convertPath(folderPath)}/${filePath}`,
두분 코멘트 확인했습니다 !
민석님이 PR 올리셨던 코드 중에서 [constants/paths.js](https://github.com/KrossCutting/KrossCutting-server/pull/4/files/30e7583fd45d88b6524fe5ef8c0d81dde962284f#diff-e215cdd242c25f0b3715bc20294a290419c743efd76da53743af6832b0d897c2)가 있어서,
해당 경로를 import 하여 사용하면 될 것 같습니다 !
감사합니다 ( _ _ )

2024-02-04 07:36 UTC, alswla approved these changes, later dismissed
변경사항 모두 확인했습니다. 수고하셨습니다 수진님!!🔥

2024-02-04 08:43 UTC, sht02048 requested changes

2024-02-04 08:43 UTC, sht02048 commented on routes/controllers/videoFrame.controller.js
> +        return extractFramesFromVideo(
수진님 return문이 if 절 바로 뒤에 위치해서 인덴팅을 해주시면 가독성이 더 좋을 것 같습니다!

2024-02-04 09:39 UTC, sht02048 approved these changes

2024-02-04 09:41 UTC, alswla approved these changes
수고하셨습니다 수진님!! 🔥

2024-02-04 09:41 UTC, merged