Feat. 교체할 프레임에 대한 이미지 크기 비교 분석 기능 개발
KrossCutting/KrossCutting-server pull request #7
Opened 2024-02-06 11:56 UTC by zzinLee

# KanBan Title
- [교체될 서브영상 구간에 대해 이미지 크기 비교분석](https://www.notion.so/minsug/Server-compliations-POST-1-83dadb4a91d44626baf061737c5875b8?pvs=4)

# Tasks in detail - checkList
- [x]  전 단계에서 실행된 함수의 반환값(교차편집 구간)을 기반으로 교차편집이 시작되는 서브영상의 첫번째 프레임 이미지와 해당 프레임의 직전 메인영상 프레임에 Sharp를 통해 diff 값을 분석
- [x]  메인영상에 대해 교차편집이 들어갈 영상의 프레임을 확인하여 차이가 날 경우 차이가나는 비율만큼 작은 영상을 확대
- [x]  확대가 진행된 프레임을 기존 영상의 경로에 덮어 씌우기

# Description
로직구현사항은 아래와 같습니다.
비교하고자 하는 이미지가 아래와 같이 생성됩니다.
라이브러리에서 제공하는 좌표값을 통해 그림을 그려 알 수 있습니다.

![resizeNingNing](https://github.com/KrossCutting/KrossCutting-server/assets/91821887/569ad630-a021-4181-a739-13f44a4cf224)

이들의 비율을 이용하여, 작은 이미지가 큰 이미지만큼 확대되도록 하고 규격에 맞게 자릅니다.

![resize전](https://github.com/KrossCutting/KrossCutting-server/assets/91821887/9891a538-1a05-411e-aa0f-62b32511342b)
이미지 편집 전

![resize후](https://github.com/KrossCutting/KrossCutting-server/assets/91821887/2dafbbd4-4eb7-431c-8bc1-3b0b9a898526)

이미지 편집 후

# Concern
-[확대 완료된 이미지를 편집하는 로직](https://github.com/KrossCutting/KrossCutting-server/compare/Feat/face-analyze?expand=1#diff-26435bf51f49ae0f542bcf80e3638758929f19fed42490cf567cf75b9a9fefceR54-R55)에 대한 더 좋은 아이디어가 있다면 제안해주세요!
현재는 원샷이 가운데에 있다는 전제하에 증가율을 통해 연산하였습니다.
- 원샷 구간이 있다는 전제하에 함수를 작성하였습니다. 추후 전작업과 연결하면서 예외처리 리팩터링 예정입니다.

# remarks
- **Add dependency** [패키지가 추가](https://github.com/KrossCutting/KrossCutting-server/compare/Feat/face-analyze?expand=1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R15-R17)되었습니다! 
- [사용되지 않는 변수](https://github.com/KrossCutting/KrossCutting-server/compare/Feat/face-analyze?expand=1#diff-26435bf51f49ae0f542bcf80e3638758929f19fed42490cf567cf75b9a9fefceR17-R25)들이 있습니다. 이들은 추후 사용가능성을 염두에 두고 일부러 제거하지 않았습니다. 추후 변동사항에 따라 정리할 예정입니다.
- [ES Lint주의사항을 제거](https://github.com/KrossCutting/KrossCutting-server/compare/Feat/face-analyze?expand=1#diff-7c07089fe59b419e5336722c6447942835c67f5ad2809942afeae4e211537b82R7)하였습니다. 조사결과 현재 상황의 경우, async 콜백을 통해 값을 받아 사용한 후 Promise를 반환하므로 잘못된 사용법이 아니라는 판단입니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-07 03:36 UTC, sht02048 commented on constants/paths.js
> +  VIDEOS: path.join(__dirname, "../temp/videos"),
VIDEOS path를 사용하려면 TEMP_DIR_VIDEOS.VIDEOS가 되어야하는데 조금 어색한 것 같아서 변수명을 변경하는 것은 어떨까요? 
예를 들어,
```suggestion
  FOLDER: path.join(__dirname, "../temp/videos"),
```

2024-02-07 03:36 UTC, sht02048 commented on services/getFaceCoordinate.js
> +  // eslint-disable-next-line no-async-promise-executor
`eslint disable`을 `funcrtion` 내부에 작성하신 이유가 있으실까요? 

보통은 파일 최상단에 작성하는 것 같아서요! - [stackOverflow](https://stackoverflow.com/questions/34764287/turning-off-eslint-rule-for-a-specific-file)

2024-02-07 03:36 UTC, sht02048 commented on services/getFaceCoordinate.js
> +      const faceCoordinates = [];
여기 선언된 변수명들이 대체로 general해서 상세하게 파악하기 힘든데 이게 원래 컨벤션일까요? 만약 아니라면 대략적으로 알 수 있게 변경해주시면 추후에 작업할때 도움이 많이 될 것 같습니다!
예를 들어,
```suggestion
      const faceImgBuffer = await fs.readFile(imgPath);
      const img = await loadImage(imgBuffer);
      const canvas = createCanvas(img.width, img.height);
      const ctx = canvas.getContext("2d");

      ctx.drawImage(img, 0, 0, img.width, img.height);

      const model = await blazeface.load();
      const input = tf.browser.fromPixels(canvas);
      const predictions = await model.estimateFaces(input, false);
      const faceCoordinates = [];
```

2024-02-07 03:36 UTC, sht02048 commented on services/resizeFrames.js
> +      top: Math.floor(((ratio - 1) * metadataImg.height) / 2),
`resize`에서는 `Math.round`를 쓰셨는데 `extract`에서는 `Math.floor`를 쓰신 이유가 있으실까요?

2024-02-07 10:51 UTC, zzinLee commented on constants/paths.js
> +  VIDEOS: path.join(__dirname, "../temp/videos"),
중복된 명명이라 그렇겠네요. 지금 당장 필요하지 않아도 혹시몰라 넣어둔 경로라 보기 좋은 상태로 변경해두겠습니다!

2024-02-07 10:51 UTC, zzinLee commented on constants/paths.js
> +  VIDEOS: path.join(__dirname, "../temp/videos"),
중복된 명명이라 이게 더 좋은 것 같네요! 변경해두겠습니다.

2024-02-07 10:53 UTC, zzinLee commented on services/getFaceCoordinate.js
> +  // eslint-disable-next-line no-async-promise-executor
es-lint를 특정 줄에 대해서만 적용하고 싶을 때, 싱글주석처리를 합니다!
해당 내용은 특정 줄에서만 사용하고 꺼주고 싶어서, 
eslint-disable-next-line에 no-async-promise-executor 옵션을 주었습니다 :)

2024-02-07 11:01 UTC, alswla requested changes

2024-02-07 11:01 UTC, alswla commented on constants/paths.js
> +};
앞으로 쓸 path 들을 상수화 처리 해주셨군요 👍 
이후 사용시 용이할 것 같습니다!

2024-02-07 11:01 UTC, alswla commented on services/resizeFrames.js
> +      resolve(width1 / width2);
leftX1, topY1, width1, width2의 경우 변수명이 러프하여 좀 더 명확한 변수명이 있으면 좋을 것 같다는 의견입니다! 추가로 변수명 선언과 로직 사이 인덴팅 해주시면 좋을 것 같다는 의견입니다! :)

2024-02-07 11:01 UTC, alswla commented on services/resizeFrames.js
> +  const metadataImg = await sharp(smaller).metadata();
해당 부분도 변수명이 좀 더 자세히 들어가면 좋을 것 같습니다! 꼭 자세히가 아니더라도 `img1`, `img2`와 같이 숫자보다는 `currentFrame`, `comparedFrame` 같이 의미가 있으면 좋을 것 같다는 의견입니다 :)

같은 맥락에서 bigger, smaller 역시 `biggerFrame`, `smallerFrame`이 좋을 것 같다는 의견입니다!

2024-02-07 11:01 UTC, alswla commented on services/resizeFrames.js
> +      top: Math.floor(((ratio - 1) * metadataImg.height) / 2),
수진님! 현재 코드에서는 이미지의 위치 조정이 명시적으로 다뤄지지 않는 것 같습니다! (크기 조정 과정에서 얼굴 위치가 조정되지 않고 단순 크기만 변경) 

예를 들어, 이미지 A와 이미지 B에 있는 얼굴의 크기를 서로 일치시키려 할 때, 
단순히 크기를 조정하는 것만으로는 두 이미지에서 얼굴이 동일한 위치에 오도록 보장할 수 없습니다. 
(얼굴의 절대적인 위치(예: 이미지의 왼쪽 상단 모서리로부터의 거리)가 크기 조정 과정에서 변경되지 않기 때문)

현재는 이미지를 확대하거나 축소시에 _**이미지의 가운데를 중심으로**_ 이루어지는 것으로 보입니다. 
_**얼굴의 중심을 기준으로**_ 이미지를 재조정하는 로직을 추가한다면 더 정확한 리사이징이 가능할 것 같습니다. (아래에 제가 생각하는 로직의 순서를 적어놓았는데 이후 리팩토링 PR 작업하시면서 참고가 되면 좋겠습니다!🙇‍♀️)

1. 얼굴 영역의 box에서 각 얼굴의 중심점을 계산
2. 이 중심점을 기준으로, 각 이미지의 얼굴 위치 일치
3. 얼굴의 크기를 기준으로 이미지 크기 조정

2024-02-07 11:01 UTC, alswla commented on services/resizeFrames.js
> +        console.log(info);
콘솔 내용을 같이 써줘도 좋을 것 같습니다!

```suggestion
        console.error("이미지 생성 중 오류 발생:", err);
      } else {
        console.log("이미지 생성 성공:", info);
```

2024-02-07 11:01 UTC, alswla commented on services/resizeFrames.js
> +        return;
리턴의 경우 인덴팅 해주시면 좋을 것 같다는의견입니다! ([밑의 console.log 도 동일](https://github.com/KrossCutting/KrossCutting-server/pull/7/files#diff-26435bf51f49ae0f542bcf80e3638758929f19fed42490cf567cf75b9a9fefceR39-R40))

2024-02-08 08:30 UTC, zzinLee commented on services/resizeFrames.js
> +      top: Math.floor(((ratio - 1) * metadataImg.height) / 2),
민지님이 남겨주신 코멘트를 토대로, 현재 로직을 리팩터링 하였습니다!
예외처리 후 PR다시 업로드 하겠습니다 :)

2024-02-09 08:53 UTC, zzinLee commented on services/resizeFrames.js
> +      resolve(width1 / width2);
네, 조금 더 명시적으로 변경하는게 좋을 것 같아 mainLeft, mainRight 및 subLeft, subRight로 변경할 예정입니다!

2024-02-09 11:39 UTC, sht02048 commented on routes/controllers/extract.controller.js
> +          `./${convertPath(folderPath)}`,
수진님! `TEMP_DIR_VIDEOS.FORDER`가 `/temp/videos` 로 끝나는데 그 뒤에 ./가 오면 오류가 나지 않나요?  이어주는 구간에 `"."`를 붙이신 이유가 있나요?

2024-02-09 11:39 UTC, sht02048 commented on services/resizeFrames.js
> +      return null;
개인적인 궁금한 것이 있는데요 수진님! 그냥 `return`이 아니라` return null`을 하신 이유가 있으실까요? 저도 이런 경우에 어떻게 해야할지 기준이 없는데 수진님은 있으신가해서 여쭤봅니다!

2024-02-09 12:03 UTC, alswla requested changes
수진님! 좌표 계산하는 것이 쉽지 않으셨을텐데 엣지케이스에 대해서도 하나하나 세밀하게 신경쓰신 것 같습니다👍  수고 많으셨고 함수명에 대한 코멘트만 확인 부탁드립니다!! 🙇‍♀️

2024-02-09 12:03 UTC, alswla commented on services/resizeFrames.js
> +    if (mainFaceCoord.y > subFaceCoord.y) {
전체적인 크기가 다를 경우와 위치만 다를경우의 조건을 별도로 해서 구해주시는군요 👍

2024-02-09 12:03 UTC, alswla commented on services/resizeFrames.js
> +    };
얼굴을 기준으로 좌표를 이동시키므로 더 정확한 크기 조정이 가능할 것 같습니다 👍

2024-02-09 12:03 UTC, alswla commented on services/resizeFrames.js
> +    Math.abs(mainFaceCoord.y - subFaceCoord.y) > imgMetadata.height / 4;
수진님! 이 4라는 기준은 하나의 프레임에서의 구역을 4등분한 것으로 보이는데 두 프레임간의 차이가 구역의 1/4보다 클 경우를 얻고, 그 경우에는 (아래 코드를 참고해보니) 여러명의 얼굴이 있을 경우를 대비하신 것으로 보입니다! 제 이해가 맞을까요? (혹은 너무 큰 차이가 있을 경우) 🤔

그렇다면 다른 얼굴 혹은 너무 먼 위치의 얼굴 즉 유효하지 않은 값을 확인하고 있고, 리턴값은 불리언이기 때문에 `isValidFacePosition`혹은 `isSameFace`과 같이 변경하는 것이 좋을 것 같다는 의견입니다!👍

2024-02-09 12:03 UTC, alswla commented on services/resizeFrames.js
> +      console.log("같은 얼굴이 아닙니다.  임의로 사이즈를 조정합니다.");
같은 얼굴이 아니더라도 큰 차이가 날 수 있는 부분이라면 유효범위보다 큰 차이를 가진다는 내용도 같이 들어가면 좋을 것 같다고 생각했는데, 혹시 같은 얼굴이 아닐 경우에는 큰 차이가 날 수 없는 부분인지 궁금합니다!🤔

2024-02-09 12:03 UTC, alswla commented on services/resizeFrames.js
> +        }
메인/서브 중 작은 이미지에 대해 리사이즈를 진행하고 나서 서브이미지를 한번 더 검사하여 세밀한 위치를 조정해 주시는 것 같습니다 👍

2024-02-10 07:24 UTC, zzinLee commented on routes/controllers/extract.controller.js
> +          `./${convertPath(folderPath)}`,
`path.join()` 연산을 통하여 진행하면, "./"는 문자열이 아닌 현재 폴더의 위치로 조회되는 것으로 알고 있습니다!

아래에 예시를 참고해 주세요 :) 
```js
const { TEMP_DIR_VIDEOS } = require("../../constants/paths");
const imgPath = path.join(TEMP_DIR_VIDEOS.FORDER, "./main-contents/");

console.log(imgPath);
```

연산 시 아래와 같이 로그가 찍히게 됩니다.
/Users/사용자이름/Desktop/TJ95-KrossCutting/KrossCutting-server/temp/videos/main-contents/

2024-02-10 07:27 UTC, zzinLee commented on services/resizeFrames.js
> +      return null;
ES Lint 사용 시 `constant return`을 요청하고 있어서 현재 `return null`을 사용하고 있습니다.
`return;` 사용시에는 명시적이지 않은 값이라는 린트 오류가 생성되기 때문에 
우선적으로 `null`을 사용하고 있는데요, 저도 여전히 고민 중에 있습니다.

기존 암시적 `return` 은 `undefined`를 `return` 하기 때문에 `undefined`를 쓰는 것이 맞지 않나 라는 고민도 되네요..

현재에는 어차피 오류 핸들링이 되어 있지 않은 상태이고,
해당 `null`이 `return` 되는 구간에 적절한 처리를 해주어야 하는 경우도 있을 것 같아서 `null`로 처리해두었습니다.

2024-02-10 07:29 UTC, zzinLee commented on services/resizeFrames.js
> +    Math.abs(mainFaceCoord.y - subFaceCoord.y) > imgMetadata.height / 4;
코드의 의도를 정확하게 이해하셨습니다 :) 
사실 원래 `isSameFace`라는 함수명을 지었다가 변경하였습니다.
민지님의 리뷰를 다시 살펴보니, 기존의 함수명이 더 명시적인 것 같네요. 변경하도록 하겠습니다 !

2024-02-10 07:45 UTC, zzinLee commented on services/resizeFrames.js
> +      console.log("같은 얼굴이 아닙니다.  임의로 사이즈를 조정합니다.");
같은 얼굴이 아니더라도 큰 차이가 날 수 없는지에 대한 의문을 주셨는데요,
민지님의 의문을 제가 정확히 이해하지 못한 것 같네요..🥹
그래도 제가 생각한 답변을 드리고자 합니다!

제가 검사하게 되는 대상 프레임들은 이미 전처리를 모두 거친 프레임이므로,
같은 구간의 (같은 시간대의) 서로 다른 영상의 프레임을 검사하게 됩니다.
즉 같은 원샷 구간 이여야 하고 이를 편집하기 위해 검사를 진행합니다.

해당 함수는 유사한 위치가 아닌 얼굴이라면 `false`를 유사한 위치에 있는 얼굴이라면 `true`를 반환합니다.
서로 다른 얼굴이라면, 프레임의 가로 혹은 세로 길이의 1/4값 이상 만큼의 차이가 있다라는 전제하에 진행하였습니다.
(한정된 프레임 내에 얼굴을 감지하는 것이므로 임계값과 같은 역할을 한다고 생각해주시면 될 것 같아요)

따라서 원샷이 잡힌 프레임 기준으로 서로 다른 위치에 있는 얼굴이 감지되면,
해당 임계값을 넘는 값(widthDiff, heightDiff)임을 확인하고 `false`를 반환하게 됩니다.

추가적으로, 꼭 같은 얼굴이 아니더라도 좌표 값 사이에 큰 차이가 나지 않아 해당 함수의 `return` 값이 `true`로 나온다고 해도,
프레임 조정에는 큰 문제가 없을 것이라고 생각하여 해당 예외케이스는 따로 생각하지 않았습니다.

2024-02-10 08:06 UTC, zzinLee commented on services/getFaceCoordinate.js
> +      const faceCoordinates = [];
해당 함수는 util 함수에서 처리해주고 있어 삭제했습니다. 좋은 피드백 감사합니다 민석님!

2024-02-10 08:07 UTC, zzinLee commented on services/resizeFrames.js
> +      top: Math.floor(((ratio - 1) * metadataImg.height) / 2),
실수를 한 것 같네요.. 죄송합니다! 
해당 내용 반영하여 수정 하였으니 확인부탁드리겠습니다 :)

2024-02-10 09:00 UTC, zzinLee commented on services/resizeFrames.js
> +        }
민지님, 해당 함수는 확인해보니 subImg 뿐만 아니라 mainImg도 변경하고 있었습니다!
한번 더 짚어주신 덕분에 확인해 볼 수 있었어요.
우선 해당 내용은 다시 한번 변경하였습니다.

본디 해당 if문은 같은 위치에 얼굴이 있지 않으면,
각각의 탐지된 얼굴의 width값을 비교하여 일정비율로 늘려주는 함수입니다.
그다지 좋은 로직이 아니라고 생각이 되기는 하는데요..

그런데 현재 민지님이 작성하신 유틸함수에 의해 예외케이스가 발동되지 않고 있어,
해당 if문이 필요 없을 것으로 보여요.
이점에 대해 함께 이야기 나눠보시고, if문 내 내용을 버려도 괜찮을 것 같습니다!

2024-02-10 09:04 UTC, sht02048 approved these changes
모두 확인했습니다! 로직 구상하시느라 수고많으셨습니다 수진님! 어려우셨을텐데 고생하셨어요

2024-02-10 09:31 UTC, alswla approved these changes
수고하셨습니다 수진님!🔥

2024-02-10 09:43 UTC, merged